/**
 * Interpretation Interface - The Result of Understanding
 * 
 * Represents the cognitive product of elaborative processing.
 * While Elaboration is the process of questioning and expanding,
 * Interpretation is the synthesized understanding that emerges.
 * 
 * Theoretical Foundation:
 * - Hermeneutics: The theory and practice of interpretation
 *   (Gadamer, 1960, "Truth and Method")
 * - Kant's Judgment: The act of subsuming particulars under universals
 *   (Kant, 1790, "Critique of Judgment")
 * - Constructive Processing: Meaning is actively constructed
 *   (Bartlett, 1932; Neisser, 1967)
 * 
 * Design Philosophy:
 * - Interpretation is the "answer" to Elaboration's "question"
 * - Created at the Function level after synthesizing Process elaborations
 * - Contains the semantic understanding generated by LLM
 * - Represents a moment of cognitive clarity
 */
export interface Interpretation {
  /**
   * The interpreted content from LLM processing
   * This is the semantic understanding that emerges from elaboration
   */
  content: unknown
  
  /**
   * Optional confidence or certainty level
   * How certain is the system about this interpretation?
   */
  confidence?: number
  
  /**
   * Optional alternative interpretations
   * Cognitive systems often generate multiple possible meanings
   */
  alternatives?: unknown[]
  
  /**
   * The source or basis for this interpretation
   * Which cognitive function produced this understanding?
   */
  source?: string
}